from __future__ import annotations

from typing import Protocol, Tuple, runtime_checkable, Any, Self, TypeAlias

from ._dtype import DType

Shape: TypeAlias = Tuple[int, ...]


@runtime_checkable
class ArrayLike(Protocol):
    @property
    def shape(self) -> Shape: ...
    @property
    def dtype(self) -> DType: ...
    def conj(self) -> Self: ...
    @property
    def T(self) -> Self: ...


class SparseArray(ArrayLike, Protocol):
    def reshape(self, shape: Shape) -> Self: ...


class DenseArray(ArrayLike, Protocol):
    @property
    def ndim(self) -> int: ...
    @property
    def real(self) -> Self: ...
    @property
    def imag(self) -> Self: ...

    def astype(self, dtype: DType, /, *args: Any, **kwargs: Any) -> Self: ...
    def reshape(self, *shape: int) -> Self: ...
    def transpose(self, *axes: int) -> Self: ...
    def conj(self) -> Self: ...

    def __getitem__(self, key: Any) -> Any: ...

    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...
    def __abs__(self) -> Self: ...

    def __add__(self, other: Any) -> Self: ...
    def __radd__(self, other: Any) -> Self: ...
    def __sub__(self, other: Any) -> Self: ...
    def __rsub__(self, other: Any) -> Self: ...
    def __mul__(self, other: Any) -> Self: ...
    def __rmul__(self, other: Any) -> Self: ...
    def __truediv__(self, other: Any) -> Self: ...
    def __rtruediv__(self, other: Any) -> Self: ...
    def __pow__(self, other: Any) -> Self: ...
    def __rpow__(self, other: Any) -> Self: ...
    def __matmul__(self, other: Any) -> Self: ...
    def __rmatmul__(self, other: Any) -> Self: ...

    def __lt__(self, other: Any) -> Any: ...
    def __le__(self, other: Any) -> Any: ...
    def __gt__(self, other: Any) -> Any: ...
    def __ge__(self, other: Any) -> Any: ...
