from __future__ import annotations

from typing import Protocol, Tuple, runtime_checkable, Any, Union

from ._dtype import DType


@runtime_checkable
class DenseArray(Protocol):
    @property
    def shape(self) -> Tuple[int, ...]: ...
    @property
    def dtype(self) -> DType: ...
    @property
    def real(self) -> "DenseArray": ...
    @property
    def imag(self) -> "DenseArray": ...

    def conj(self) -> "DenseArray": ...
    @property
    def T(self) -> "DenseArray": ...

    def reshape(self, shape: Tuple[int, ...]) -> "DenseArray": ...

    def astype(self, dtype: DType) -> "DenseArray": ...

    def __add__(self, other: "DenseArray") -> "DenseArray": ...
    def __sub__(self, other: "DenseArray") -> "DenseArray": ...
    def __mul__(self, other: Any) -> "DenseArray": ...
    def __rmul__(self, other: Any) -> "DenseArray": ...
    def __matmul__(self, other: "DenseArray") -> "DenseArray": ...
    def __rmatmul__(self, other: "DenseArray") -> "DenseArray": ...
    def __truediv__(self, other: "DenseArray") -> "DenseArray": ...
    def __rtruediv__(self, other: "DenseArray") -> "DenseArray": ...
    def __getitem__(self, item: Union[int, slice, tuple]) -> "DenseArray": ...
    def __neg__(self) -> "DenseArray": ...

    def max(self) -> Any: ...
    def min(self) -> Any: ...
    def sum(self) -> Any: ...
    def abs(self) -> "DenseArray": ...

