"""Backend-agnostic vector spaces, linear operators, and solvers."""

from ._version import __version__

from .backend import CHECK_LEVELS, CheckLevel, Context, BackendOps, NumpyOps, jax_pytree_class

try:
    from .backend import JaxOps as JaxOps
except ImportError:
    pass
try:
    from .backend import CuPyOps as CuPyOps
except ImportError:
    pass
try:
    from .backend import TorchOps as TorchOps
except ImportError:
    pass
from .linop import (
    BlockDiagonalLinOp,
    BlockMatrixLinOp,
    ComposedLinOp,
    DiagonalLinOp,
    DenseLinOp,
    IdentityLinOp,
    LinOp,
    MatrixFreeLinOp,
    TreeLinOp,
    ScaledLinOp,
    SparseLinOp,
    StackedLinOp,
    SumLinOp,
    SumToSingleLinOp,
    ZeroLinOp,
    make_composed,
    make_scaled,
    make_sum,
)
from .functional import (
    ComposedFunctional,
    Functional,
    HuberFunctional,
    InnerProductFunctional,
    KLDivergenceFunctional,
    L1NormFunctional,
    LinearFunctional,
    LinOpQuadraticForm,
    LpNormFunctional,
    MatrixFreeLinearFunctional,
    NegativeEntropyFunctional,
    NuclearNormFunctional,
    QuadraticForm,
    SpectralLpNormFunctional,
    SquaredL2NormFunctional,
    generalized_shrinkage,
    least_squares,
    make_functional_composed,
    project_nonneg,
    prox_l1,
    prox_l2sq,
)
from .linalg import (
    CGResult,
    ExpmMultiplyResult,
    LanczosResult,
    LSQRResult,
    PowerIterationResult,
    cg,
    expm_multiply,
    lanczos_smallest,
    lsqr,
    power_iteration,
)
from .optimize import (
    OptaxResult,
    line_search_scipy,
    minimize_optax,
    minimize_scipy,
)
from .space import (
    BackendCheck,
    DTypeCheck,
    FieldCheck,
    HermitianCheck,
    CoordinateSpace,
    DenseCoordinateSpace,
    DenseVectorSpace,
    ElementwiseJordanSpace,
    EuclideanElementwiseJordanSpace,
    EuclideanJordanAlgebraSpace,
    InnerProductSpace,
    JordanAlgebraSpace,
    StackedSpace,
    TreeElement,
    TreeSpace,
    TreeSpectralDecomposition,
    ShapeCheck,
    InnerProduct,
    EuclideanInnerProduct,
    WeightedInnerProduct,
    Space,
    StarSpace,
    SpaceCheck,
    SpaceValidationError,
    SquareMatrixCheck,
    VectorSpace,
    HermitianSpace,
)
from .types import DenseArray, SparseArray, ArrayLike

from ._checks import checked_method
from ._contextual import (
    ContextBound,
    set_context,
    get_context,
    resolve_context_priority,
    register_ops,
    normalize_ops,
    normalize_context,
)

__all__ = [
    "__version__",
    "Context",
    "CheckLevel",
    "CHECK_LEVELS",
    "BackendOps",
    "jax_pytree_class",
    "NumpyOps",
    "LinOp",
    "ComposedLinOp",
    "DiagonalLinOp",
    "DenseLinOp",
    "IdentityLinOp",
    "MatrixFreeLinOp",
    "ScaledLinOp",
    "SparseLinOp",
    "SumLinOp",
    "ZeroLinOp",
    "make_composed",
    "make_scaled",
    "make_sum",
    "TreeLinOp",
    "BlockDiagonalLinOp",
    "BlockMatrixLinOp",
    "SumToSingleLinOp",
    "StackedLinOp",
    "ComposedFunctional",
    "Functional",
    "LinearFunctional",
    "InnerProductFunctional",
    "MatrixFreeLinearFunctional",
    "QuadraticForm",
    "LinOpQuadraticForm",
    "make_functional_composed",
    "least_squares",
    "SquaredL2NormFunctional",
    "LpNormFunctional",
    "L1NormFunctional",
    "NegativeEntropyFunctional",
    "KLDivergenceFunctional",
    "HuberFunctional",
    "SpectralLpNormFunctional",
    "NuclearNormFunctional",
    "generalized_shrinkage",
    "prox_l1",
    "prox_l2sq",
    "project_nonneg",
    "CGResult",
    "ExpmMultiplyResult",
    "LanczosResult",
    "LSQRResult",
    "PowerIterationResult",
    "cg",
    "expm_multiply",
    "lanczos_smallest",
    "lsqr",
    "power_iteration",
    "minimize_scipy",
    "minimize_optax",
    "OptaxResult",
    "line_search_scipy",
    "BackendCheck",
    "DTypeCheck",
    "FieldCheck",
    "HermitianCheck",
    "ShapeCheck",
    "InnerProduct",
    "EuclideanInnerProduct",
    "WeightedInnerProduct",
    "VectorSpace",
    "HermitianSpace",
    "StackedSpace",
    "TreeElement",
    "TreeSpace",
    "TreeSpectralDecomposition",
    "CoordinateSpace",
    "InnerProductSpace",
    "StarSpace",
    "JordanAlgebraSpace",
    "EuclideanJordanAlgebraSpace",
    "DenseCoordinateSpace",
    "DenseVectorSpace",
    "ElementwiseJordanSpace",
    "EuclideanElementwiseJordanSpace",
    "Space",
    "SpaceCheck",
    "SpaceValidationError",
    "SquareMatrixCheck",
    "DenseArray",
    "SparseArray",
    "ArrayLike",
    "checked_method",
    "ContextBound",
    "set_context",
    "get_context",
    "resolve_context_priority",
    "register_ops",
    "normalize_ops",
    "normalize_context",
]

if "JaxOps" in globals():
    __all__.append("JaxOps")
if "TorchOps" in globals():
    __all__.append("TorchOps")
if "CuPyOps" in globals():
    __all__.append("CuPyOps")
