"""Backend-agnostic vector spaces, linear operators, and solvers."""

from ._version import __version__

from .contextual import Context
from .backend import CHECK_LEVELS, CheckLevel, BackendOps, NumpyOps
from .backend._optional import available_ops as _available_ops
from .linop import (
    BlockDiagonalLinOp,
    BlockMatrixLinOp,
    ComposedLinOp,
    DiagonalLinOp,
    DenseLinOp,
    IdentityLinOp,
    LinOp,
    MatrixFreeLinOp,
    TreeLinOp,
    ScaledLinOp,
    SparseLinOp,
    StackedLinOp,
    SumLinOp,
    SumToSingleLinOp,
    ZeroLinOp,
    make_composed,
    make_scaled,
    make_sum,
)
from .functional import (
    RealifiedFunctional,
    realify,
    SpectralFunctional,
    eigenvalue_space,
    spectralize,
    ComposedFunctional,
    Functional,
    ConstantFunctional,
    HuberFunctional,
    InnerProductFunctional,
    KLDivergenceFunctional,
    L1NormFunctional,
    LinearFunctional,
    LinOpQuadraticForm,
    LpNormFunctional,
    MatrixFreeLinearFunctional,
    NegativeEntropyFunctional,
    NuclearNormFunctional,
    ProductFunctional,
    QuadraticForm,
    ScaledFunctional,
    ShiftedFunctional,
    SquaredL2NormFunctional,
    SumFunctional,
    ZeroFunctional,
    generalized_shrinkage,
    least_squares,
    make_constant_functional,
    make_functional_composed,
    make_functional_product,
    make_functional_sum,
    make_scaled_functional,
    make_shifted_functional,
    project_nonneg,
    prox_l1,
    prox_l2sq,
)
from .opfamily import (
    FunctionalScaledOperator,
    OperatorFamily,
    make_functional_scaled_operator,
)
from .linalg import (
    CGResult,
    ExpmMultiplyResult,
    LanczosResult,
    LSQRResult,
    PowerIterationResult,
    cg,
    expm_multiply,
    lanczos_smallest,
    lsqr,
    power_iteration,
)
from .optimize import (
    OptaxResult,
    line_search_scipy,
    minimize_optax,
    minimize_scipy,
)
from .space import (
    BackendCheck,
    DTypeCheck,
    FieldCheck,
    HermitianCheck,
    CoordinateSpace,
    DenseCoordinateSpace,
    DenseVectorSpace,
    ElementwiseJordanSpace,
    EuclideanElementwiseJordanSpace,
    EuclideanJordanAlgebraSpace,
    InnerProductSpace,
    JordanAlgebraSpace,
    StackedSpace,
    TreeElement,
    TreeSpace,
    TreeSpectralDecomposition,
    ShapeCheck,
    InnerProduct,
    EuclideanInnerProduct,
    WeightedInnerProduct,
    Space,
    StarSpace,
    SpaceCheck,
    SpaceValidationError,
    SquareMatrixCheck,
    VectorSpace,
    HermitianSpace,
)
from .types import DenseArray, SparseArray, ArrayLike

from ._checks import checked_method
from .contextual import (
    ContextBound,
    set_context,
    get_context,
    set_check_level,
    get_check_level,
    use_check_level,
    use_context,
    resolve_context_priority,
    register_ops,
    normalize_ops,
    normalize_context,
)

# Re-export each optional backend whose dependency is importable (JaxOps,
# CuPyOps, TorchOps). Mirrors the backend package: one loop over the single
# source of truth in ``backend._optional`` (a missing dependency is skipped, a
# broken install warns and is skipped) instead of per-backend try/except.
_optional_ops = _available_ops()
for _cls in _optional_ops:
    globals().setdefault(_cls.__name__, _cls)

__all__ = [
    "__version__",
    "Context",
    "CheckLevel",
    "CHECK_LEVELS",
    "BackendOps",
    "NumpyOps",
    "LinOp",
    "ComposedLinOp",
    "DiagonalLinOp",
    "DenseLinOp",
    "IdentityLinOp",
    "MatrixFreeLinOp",
    "ScaledLinOp",
    "SparseLinOp",
    "SumLinOp",
    "ZeroLinOp",
    "make_composed",
    "make_scaled",
    "make_sum",
    "TreeLinOp",
    "BlockDiagonalLinOp",
    "BlockMatrixLinOp",
    "SumToSingleLinOp",
    "StackedLinOp",
    "ComposedFunctional",
    "FunctionalScaledOperator",
    "Functional",
    "LinearFunctional",
    "InnerProductFunctional",
    "MatrixFreeLinearFunctional",
    "QuadraticForm",
    "LinOpQuadraticForm",
    "ScaledFunctional",
    "ConstantFunctional",
    "ProductFunctional",
    "ShiftedFunctional",
    "SumFunctional",
    "ZeroFunctional",
    "make_functional_composed",
    "make_functional_sum",
    "make_scaled_functional",
    "make_constant_functional",
    "make_functional_scaled_operator",
    "make_functional_product",
    "make_shifted_functional",
    "least_squares",
    "SquaredL2NormFunctional",
    "LpNormFunctional",
    "L1NormFunctional",
    "NegativeEntropyFunctional",
    "KLDivergenceFunctional",
    "HuberFunctional",
    "RealifiedFunctional",
    "SpectralFunctional",
    "NuclearNormFunctional",
    "OperatorFamily",
    "eigenvalue_space",
    "realify",
    "spectralize",
    "generalized_shrinkage",
    "prox_l1",
    "prox_l2sq",
    "project_nonneg",
    "CGResult",
    "ExpmMultiplyResult",
    "LanczosResult",
    "LSQRResult",
    "PowerIterationResult",
    "cg",
    "expm_multiply",
    "lanczos_smallest",
    "lsqr",
    "power_iteration",
    "minimize_scipy",
    "minimize_optax",
    "OptaxResult",
    "line_search_scipy",
    "BackendCheck",
    "DTypeCheck",
    "FieldCheck",
    "HermitianCheck",
    "ShapeCheck",
    "InnerProduct",
    "EuclideanInnerProduct",
    "WeightedInnerProduct",
    "VectorSpace",
    "HermitianSpace",
    "StackedSpace",
    "TreeElement",
    "TreeSpace",
    "TreeSpectralDecomposition",
    "CoordinateSpace",
    "InnerProductSpace",
    "StarSpace",
    "JordanAlgebraSpace",
    "EuclideanJordanAlgebraSpace",
    "DenseCoordinateSpace",
    "DenseVectorSpace",
    "ElementwiseJordanSpace",
    "EuclideanElementwiseJordanSpace",
    "Space",
    "SpaceCheck",
    "SpaceValidationError",
    "SquareMatrixCheck",
    "DenseArray",
    "SparseArray",
    "ArrayLike",
    "checked_method",
    "ContextBound",
    "set_context",
    "get_context",
    "set_check_level",
    "get_check_level",
    "use_check_level",
    "use_context",
    "resolve_context_priority",
    "register_ops",
    "normalize_ops",
    "normalize_context",
]

__all__ += [_cls.__name__ for _cls in _optional_ops if _cls.__name__ != "NumpyOps"]
