"""Vector space abstractions, concrete spaces, and validation checks."""

from .._errors import CapabilityError
from .checks import (
    BackendCheck,
    DTypeCheck,
    FieldCheck,
    HermitianCheck,
    ShapeCheck,
    SpaceCheck,
    SpaceValidationError,
    SquareMatrixCheck,
)
from .base import (
    Field,
    RealField,
    ComplexField,
    CoordinateSpace,
    EuclideanInnerProduct,
    EuclideanJordanAlgebraSpace,
    InnerProduct,
    InnerProductSpace,
    JordanAlgebraSpace,
    Space,
    StarSpace,
    VectorSpace,
    WeightedInnerProduct,
)
from .concrete import (
    DenseCoordinateSpace,
    DenseVectorSpace,
    ElementwiseJordanSpace,
    EuclideanElementwiseJordanSpace,
    HermitianSpace,
    StackedSpace,
    TreeElement,
    TreeSpace,
    TreeSpectralDecomposition,
)

__all__ = [
    "BackendCheck",
    "DTypeCheck",
    "FieldCheck",
    "HermitianCheck",
    "ShapeCheck",
    "InnerProduct",
    "EuclideanInnerProduct",
    "WeightedInnerProduct",
    "Field",
    "RealField",
    "ComplexField",
    "CoordinateSpace",
    "InnerProductSpace",
    "StarSpace",
    "JordanAlgebraSpace",
    "EuclideanJordanAlgebraSpace",
    "DenseCoordinateSpace",
    "DenseVectorSpace",
    "ElementwiseJordanSpace",
    "EuclideanElementwiseJordanSpace",
    "HermitianSpace",
    "StackedSpace",
    "TreeElement",
    "TreeSpace",
    "TreeSpectralDecomposition",
    "Space",
    "SpaceCheck",
    "CapabilityError",
    "SpaceValidationError",
    "SquareMatrixCheck",
    "VectorSpace",
]
