"""Vector space abstractions, concrete spaces, and validation checks."""

from .checks import (
    BackendCheck,
    DTypeCheck,
    HermitianCheck,
    ProductComponentCheck,
    ProductStructureCheck,
    ShapeCheck,
    SpaceCheck,
    SpaceValidationError,
    SquareMatrixCheck,
)
from .base import (
    CoordinateSpace,
    EuclideanInnerProduct,
    EuclideanJordanAlgebraSpace,
    InnerProduct,
    InnerProductSpace,
    JordanAlgebraSpace,
    Space,
    StarSpace,
    VectorSpace,
    WeightedInnerProduct,
)
from .concrete import (
    DenseCoordinateSpace,
    DenseVectorSpace,
    ElementwiseJordanSpace,
    HermitianSpace,
    ProductEuclideanJordanAlgebraSpace,
    ProductInnerProductSpace,
    ProductJordanAlgebraSpace,
    ProductSpace,
    ProductStarSpace,
    StackedEuclideanJordanAlgebraSpace,
    StackedInnerProductSpace,
    StackedJordanAlgebraSpace,
    StackedSpace,
    StackedStarSpace,
)
from ._structure import ProductStructure, PytreeStructure, TupleStructure

__all__ = [
    "BackendCheck",
    "DTypeCheck",
    "HermitianCheck",
    "ProductComponentCheck",
    "ProductStructureCheck",
    "ShapeCheck",
    "InnerProduct",
    "EuclideanInnerProduct",
    "WeightedInnerProduct",
    "CoordinateSpace",
    "InnerProductSpace",
    "StarSpace",
    "JordanAlgebraSpace",
    "EuclideanJordanAlgebraSpace",
    "DenseCoordinateSpace",
    "DenseVectorSpace",
    "ElementwiseJordanSpace",
    "HermitianSpace",
    "ProductSpace",
    "ProductInnerProductSpace",
    "ProductStarSpace",
    "ProductJordanAlgebraSpace",
    "ProductEuclideanJordanAlgebraSpace",
    "ProductStructure",
    "TupleStructure",
    "PytreeStructure",
    "StackedSpace",
    "StackedInnerProductSpace",
    "StackedStarSpace",
    "StackedJordanAlgebraSpace",
    "StackedEuclideanJordanAlgebraSpace",
    "Space",
    "SpaceCheck",
    "SpaceValidationError",
    "SquareMatrixCheck",
    "VectorSpace",
]
