"""Vector space abstractions, concrete spaces, and validation checks."""

from .checks import (
    BackendCheck,
    DTypeCheck,
    FieldCheck,
    HermitianCheck,
    ProductComponentCheck,
    ProductStructureCheck,
    ShapeCheck,
    SpaceCheck,
    SpaceValidationError,
    SquareMatrixCheck,
)
from .base import (
    CoordinateSpace,
    EuclideanInnerProduct,
    EuclideanJordanAlgebraSpace,
    InnerProduct,
    InnerProductSpace,
    JordanAlgebraSpace,
    Space,
    StarSpace,
    VectorSpace,
    WeightedInnerProduct,
)
from .concrete import (
    DenseCoordinateSpace,
    DenseVectorSpace,
    ElementwiseJordanSpace,
    EuclideanElementwiseJordanSpace,
    HermitianSpace,
    ProductSpace,
    ProductSpectralDecomposition,
    StackedSpace,
)
from ._structure import ProductStructure, PytreeStructure, TupleStructure

__all__ = [
    "BackendCheck",
    "DTypeCheck",
    "FieldCheck",
    "HermitianCheck",
    "ProductComponentCheck",
    "ProductStructureCheck",
    "ShapeCheck",
    "InnerProduct",
    "EuclideanInnerProduct",
    "WeightedInnerProduct",
    "CoordinateSpace",
    "InnerProductSpace",
    "StarSpace",
    "JordanAlgebraSpace",
    "EuclideanJordanAlgebraSpace",
    "DenseCoordinateSpace",
    "DenseVectorSpace",
    "ElementwiseJordanSpace",
    "EuclideanElementwiseJordanSpace",
    "HermitianSpace",
    "ProductSpace",
    "ProductSpectralDecomposition",
    "ProductStructure",
    "TupleStructure",
    "PytreeStructure",
    "StackedSpace",
    "Space",
    "SpaceCheck",
    "SpaceValidationError",
    "SquareMatrixCheck",
    "VectorSpace",
]
